# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create([{name: 'User1'}, {name: 'User2'}, {name: 'User3'}, {name: 'User4'}, {name: 'User5'}])
Post.create([{post_type: 'question', body: 'Question1 User1', user_id: User.first.id}, {post_type: 'question', body: 'Question2 User2', user_id: User.second.id}, {post_type: 'question', body: 'Question3 User3', user_id: User.third.id}, {post_type: 'question', body: 'Question4 User4', user_id: User.fourth.id}, {post_type: 'question', body: 'Question5 User5', user_id: User.fifth.id}])

Post.create([{post_type: 'comment', parent_post_id: Post.question.first, body: 'Comment1 Question1 User1', user_id: User.first.id}, {post_type: 'comment', parent_post_id: Post.question.second, body: 'Comment1 Question2 User2', user_id: User.second.id}, {post_type: 'comment', parent_post_id: Post.question.third, body: 'Comment1 Question3 User3', user_id: User.third.id}, {post_type: 'comment', parent_post_id: Post.question.fourth, body: 'Comment1 Question4 User4', user_id: User.fourth.id}, {post_type: 'comment', parent_post_id: Post.question.fifth, body: 'Comment1 Question5 User5', user_id: User.fifth.id}])
Post.create([{post_type: 'comment', parent_post_id: Post.comment.first, body: 'Comment11 Question1 User1', user_id: User.first.id}, {post_type: 'comment', parent_post_id: Post.comment.first, body: 'Comment11 Question2 User2', user_id: User.second.id}, {post_type: 'comment', parent_post_id: Post.comment.first, body: 'Comment11 Question3 User3', user_id: User.third.id}, {post_type: 'comment', parent_post_id: Post.comment.first, body: 'Comment11 Question4 User4', user_id: User.fourth.id}, {post_type: 'comment', parent_post_id: Post.comment.first, body: 'Comment11 Question5 User5', user_id: User.fifth.id}])
Post.create([{post_type: 'comment', parent_post_id: Post.comment.second, body: 'Comment12 Question1 User1', user_id: User.first.id}, {post_type: 'comment', parent_post_id: Post.comment.second, body: 'Comment12 Question2 User2', user_id: User.second.id}, {post_type: 'comment', parent_post_id: Post.comment.second, body: 'Comment12 Question3 User3', user_id: User.third.id}, {post_type: 'comment', parent_post_id: Post.comment.second, body: 'Comment12 Question4 User4', user_id: User.fourth.id}, {post_type: 'comment', parent_post_id: Post.comment.second, body: 'Comment12 Question5 User5', user_id: User.fifth.id}])
